import { useState, useEffect } from "react";
import { ArrowLeft, CheckCircle2, XCircle, Trophy, Loader2 } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Input } from "@/components/ui/input";
import AppLayout from "@/components/AppLayout";
import { useAuth } from "@/contexts/AuthContext";
import { generateGrammarQuestions, GrammarQuestion } from "@/lib/gemini";
import { saveExerciseResult } from "@/lib/progressService";

type Difficulty = "beginner" | "intermediate" | "advanced";

const GrammarTest = () => {
  const { user } = useAuth();
  const [difficulty, setDifficulty] = useState<Difficulty | null>(null);
  const [questions, setQuestions] = useState<GrammarQuestion[]>([]);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [selected, setSelected] = useState("");
  const [userInput, setUserInput] = useState("");
  const [answered, setAnswered] = useState(false);
  const [score, setScore] = useState(0);
  const [finished, setFinished] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const startTest = async (diff: Difficulty) => {
    setDifficulty(diff);
    setLoading(true);
    setError("");
    try {
      const qs = await generateGrammarQuestions(diff, 5);
      setQuestions(qs);
      setCurrentIdx(0);
      setScore(0);
      setFinished(false);
    } catch (err: any) {
      setError(err.message || "Failed to generate questions");
    } finally {
      setLoading(false);
    }
  };

  const question = questions[currentIdx];

  const handleAnswer = (ans: string) => {
    if (answered) return;
    setAnswered(true);
    if (question.type === "mcq") setSelected(ans);
    if (ans.trim().toLowerCase() === question.answer.trim().toLowerCase()) {
      setScore((s) => s + 1);
    }
  };

  const nextQuestion = () => {
    setAnswered(false);
    setSelected("");
    setUserInput("");
    if (currentIdx + 1 < questions.length) {
      setCurrentIdx((c) => c + 1);
    } else {
      setFinished(true);
      // Save result
      if (user) {
        saveExerciseResult(user.uid, "grammar", score + (selected.trim().toLowerCase() === question?.answer?.trim().toLowerCase() || userInput.trim().toLowerCase() === question?.answer?.trim().toLowerCase() ? 0 : 0), questions.length).catch(console.error);
      }
    }
  };

  const reset = () => {
    setDifficulty(null);
    setQuestions([]);
    setCurrentIdx(0);
    setSelected("");
    setUserInput("");
    setAnswered(false);
    setScore(0);
    setFinished(false);
    setError("");
  };

  // Save result when finished
  useEffect(() => {
    if (finished && user) {
      saveExerciseResult(user.uid, "grammar", score, questions.length).catch(console.error);
    }
  }, [finished]);

  return (
    <AppLayout title="Grammar Test">
      <div className="px-5 py-6 max-w-2xl mx-auto">
        <Link to="/dashboard" className="inline-flex items-center gap-1 text-sm text-muted-foreground mb-6 hover:text-foreground">
          <ArrowLeft className="w-4 h-4" /> Back
        </Link>

        {/* Difficulty Selection */}
        {!difficulty && !loading && (
          <Card className="text-center p-8">
            <h2 className="text-2xl font-bold font-display mb-2">Grammar Test</h2>
            <p className="text-muted-foreground text-sm mb-6">Questions are generated by AI. Select difficulty:</p>
            <div className="grid grid-cols-3 gap-3">
              {(["beginner", "intermediate", "advanced"] as const).map((d) => (
                <Button key={d} onClick={() => startTest(d)} variant="outline" className="capitalize h-12 font-semibold">
                  {d}
                </Button>
              ))}
            </div>
          </Card>
        )}

        {/* Loading */}
        {loading && (
          <Card className="text-center p-8">
            <Loader2 className="w-10 h-10 animate-spin text-primary mx-auto mb-4" />
            <p className="text-sm text-muted-foreground">Generating questions with AI...</p>
          </Card>
        )}

        {/* Error */}
        {error && (
          <Card className="text-center p-8">
            <p className="text-destructive mb-4">{error}</p>
            <Button onClick={reset}>Try Again</Button>
          </Card>
        )}

        {/* Questions */}
        {!loading && !error && difficulty && !finished && question && (
          <>
            <div className="flex items-center justify-between mb-4">
              <span className="text-sm font-semibold capitalize">{difficulty} Level</span>
              <span className="text-sm text-muted-foreground">{currentIdx + 1}/{questions.length}</span>
            </div>
            <Progress value={((currentIdx + 1) / questions.length) * 100} className="h-2 mb-6" />

            <Card>
              <CardHeader>
                <CardTitle className="text-base font-display leading-relaxed">{question.question}</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {question.type === "mcq" && question.options ? (
                  question.options.map((opt) => {
                    const isCorrect = opt.toLowerCase() === question.answer.toLowerCase();
                    const isSelected = selected === opt;
                    return (
                      <button
                        key={opt}
                        onClick={() => handleAnswer(opt)}
                        disabled={answered}
                        className={`w-full text-left p-3 rounded-lg border text-sm font-medium transition-colors ${answered
                            ? isCorrect
                              ? "border-feature-green bg-feature-green/10 text-feature-green"
                              : isSelected
                                ? "border-destructive bg-destructive/10 text-destructive"
                                : "border-border"
                            : "border-border hover:border-primary/30 hover:bg-secondary/50"
                          }`}
                      >
                        <div className="flex items-center gap-2">
                          {answered && isCorrect && <CheckCircle2 className="w-4 h-4 text-feature-green" />}
                          {answered && isSelected && !isCorrect && <XCircle className="w-4 h-4 text-destructive" />}
                          {opt}
                        </div>
                      </button>
                    );
                  })
                ) : (
                  <div className="space-y-3">
                    <Input
                      value={userInput}
                      onChange={(e) => setUserInput(e.target.value)}
                      placeholder="Type your answer..."
                      disabled={answered}
                      onKeyDown={(e) => { if (e.key === "Enter" && userInput.trim()) handleAnswer(userInput); }}
                    />
                    {!answered && (
                      <Button onClick={() => handleAnswer(userInput)} disabled={!userInput.trim()} className="gradient-button w-full">
                        Submit
                      </Button>
                    )}
                  </div>
                )}

                {answered && (
                  <div className={`rounded-xl p-4 ${(selected || userInput).trim().toLowerCase() === question.answer.trim().toLowerCase()
                      ? "bg-feature-green/10 border border-feature-green/30"
                      : "bg-destructive/10 border border-destructive/30"
                    }`}>
                    <p className="text-sm font-semibold mb-1">
                      {(selected || userInput).trim().toLowerCase() === question.answer.trim().toLowerCase() ? "✅ Correct!" : "❌ Incorrect"}
                    </p>
                    <p className="text-sm"><strong>Answer:</strong> {question.answer}</p>
                    {question.explanation && <p className="text-xs text-muted-foreground mt-1">{question.explanation}</p>}
                  </div>
                )}

                {answered && (
                  <Button onClick={nextQuestion} className="gradient-button w-full">
                    {currentIdx + 1 < questions.length ? "Next Question" : "See Results"}
                  </Button>
                )}
              </CardContent>
            </Card>
          </>
        )}

        {/* Results */}
        {finished && (
          <Card className="text-center p-8">
            <Trophy className="w-14 h-14 text-feature-amber mx-auto mb-4" />
            <h2 className="text-2xl font-bold font-display mb-1">Test Complete!</h2>
            <p className="text-lg font-semibold text-primary mb-2">{score}/{questions.length}</p>
            <p className="text-muted-foreground text-sm mb-6">
              {score === questions.length ? "Perfect score! 🎉" : score > questions.length / 2 ? "Great job! 👏" : "Keep practicing! 💪"}
            </p>
            <div className="flex gap-3 justify-center">
              <Button onClick={reset} variant="outline">Try Again</Button>
              <Link to="/dashboard"><Button className="gradient-button">Dashboard</Button></Link>
            </div>
          </Card>
        )}
      </div>
    </AppLayout>
  );
};

export default GrammarTest;
